require 'rake/testtask'
require 'rake/gempackagetask'
require 'rake/testtask'

def gemspec
  @gemspec ||= begin
    file = File.expand_path("eson-core.gemspec")
    ::Gem::Specification.load(file)
  end
end

desc "Validates the gemspec"
task :gemspec do
  gemspec.validate
end

Rake::GemPackageTask.new(gemspec) do |pkg|
  pkg.gem_spec = gemspec
end

task :package => :gemspec

Rake::TestTask.new(:test) do |test|
  if 'jruby' == RUBY_ENGINE
    test.pattern = 'test/**/*_test.rb'
  else
    test.pattern = 'test/{http,search}/*_test.rb'
  end 
  
  test.verbose = true
end

task :seed do
  require './test/seeds/seeds'
end