language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
env:
  - ES_VERSION=0.18.7
  - ES_VERSION=0.19.1
before_install: 'echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config'
before_script: "install_elasticsearch"
