require 'rake/testtask'
require 'rubygems/package_task'
require 'rake/testtask'

def gemspec
  @gemspec ||= begin
    file = File.expand_path("eson.gemspec")
    ::Gem::Specification.load(file)
  end
end

desc "Validates the gemspec"
task :gemspec do
  gemspec.validate
end

Gem::PackageTask.new(gemspec) do |pkg|
  pkg.gem_spec = gemspec
end

task :package => :gemspec