#require 'elsearch'

require 'multi_json'

require 'elasticsearch/node'

require 'elasticsearch/client'
require 'elasticsearch/request'
require 'elasticsearch/chainable'
require 'elasticsearch/api'
require 'elasticsearch/response'
require 'elasticsearch/error'

require 'elasticsearch/shared/core/index'
require 'elasticsearch/shared/core/get'
require 'elasticsearch/shared/core/delete'
require 'elasticsearch/shared/core/search'
require 'elasticsearch/shared/core/bulk'
require 'elasticsearch/shared/core/percolate'
require 'elasticsearch/shared/core/simple_search'

require 'elasticsearch/shared/cluster/health'
require 'elasticsearch/shared/cluster/state'
require 'elasticsearch/shared/cluster/nodes'
require 'elasticsearch/shared/cluster/stats'
require 'elasticsearch/shared/cluster/shutdown'

require 'elasticsearch/shared/indices/aliases'
require 'elasticsearch/shared/indices/analyze'
require 'elasticsearch/shared/indices/clear_cache'
require 'elasticsearch/shared/indices/close_index'
require 'elasticsearch/shared/indices/create_index'
require 'elasticsearch/shared/indices/delete_index'
require 'elasticsearch/shared/indices/delete_mapping'
require 'elasticsearch/shared/indices/flush'
require 'elasticsearch/shared/indices/get_mapping'
require 'elasticsearch/shared/indices/get_settings'
require 'elasticsearch/shared/indices/open_index'
require 'elasticsearch/shared/indices/optimize'
require 'elasticsearch/shared/indices/put_mapping'
require 'elasticsearch/shared/indices/refresh'
require 'elasticsearch/shared/indices/snapshot'
require 'elasticsearch/shared/indices/status'
require 'elasticsearch/shared/indices/put_template'
require 'elasticsearch/shared/indices/get_template'
require 'elasticsearch/shared/indices/delete_template'
require 'elasticsearch/shared/indices/update_settings'