require 'echolon-core'

require 'rest-client'
require 'addressable/template'

require 'elasticsearch/http'

require 'elasticsearch/http/request'
require 'elasticsearch/http/api'

require 'elasticsearch/http/core/index'
require 'elasticsearch/http/core/get'
require 'elasticsearch/http/core/delete'
require 'elasticsearch/http/core/search'
require 'elasticsearch/http/core/delete_by_query'
require 'elasticsearch/http/core/count'
require 'elasticsearch/http/core/bulk'
require 'elasticsearch/http/core/percolate'
require 'elasticsearch/http/core/simple_search'
require 'elasticsearch/http/core/more_like_this'

require 'elasticsearch/http/cluster/health'
require 'elasticsearch/http/cluster/state'
require 'elasticsearch/http/cluster/nodes'
require 'elasticsearch/http/cluster/stats'
require 'elasticsearch/http/cluster/shutdown'

require 'elasticsearch/http/indices/aliases'
require 'elasticsearch/http/indices/analyze'
require 'elasticsearch/http/indices/clear_cache'
require 'elasticsearch/http/indices/close_index'
require 'elasticsearch/http/indices/create_index'
require 'elasticsearch/http/indices/delete_index'
require 'elasticsearch/http/indices/delete_mapping'
require 'elasticsearch/http/indices/flush'
require 'elasticsearch/http/indices/get_mapping'
require 'elasticsearch/http/indices/get_settings'
require 'elasticsearch/http/indices/open_index'
require 'elasticsearch/http/indices/optimize'
require 'elasticsearch/http/indices/put_mapping'
require 'elasticsearch/http/indices/refresh'
require 'elasticsearch/http/indices/snapshot'
require 'elasticsearch/http/indices/status'
require 'elasticsearch/http/indices/put_template'
require 'elasticsearch/http/indices/get_template'
require 'elasticsearch/http/indices/delete_template'
require 'elasticsearch/http/indices/update_settings'

require 'elasticsearch/modules/response_parser'
require 'elasticsearch/modules/status_handler'
