require 'eson-core'

require 'addressable/template'

require 'eson/http'

require 'eson/modules/status_handler'
require 'eson/modules/response_parser'

require 'eson/http/client'
require 'eson/http/request'
require 'eson/http/api'

require 'eson/http/core/index'
require 'eson/http/core/get'
require 'eson/http/core/delete'
require 'eson/http/core/search'
require 'eson/http/core/delete_by_query'
require 'eson/http/core/count'
require 'eson/http/core/bulk'
require 'eson/http/core/percolate'
require 'eson/http/core/simple_search'
require 'eson/http/core/update'
require 'eson/http/core/more_like_this'
require 'eson/http/core/msearch'
require 'eson/http/core/mget'
require 'eson/http/core/scroll'
require 'eson/http/core/validate'
require 'eson/http/core/explain'

require 'eson/http/cluster/health'
require 'eson/http/cluster/state'
require 'eson/http/cluster/nodes'
require 'eson/http/cluster/stats'
require 'eson/http/cluster/shutdown'

require 'eson/http/indices/aliases'
require 'eson/http/indices/analyze'
require 'eson/http/indices/clear_cache'
require 'eson/http/indices/close_index'
require 'eson/http/indices/create_index'
require 'eson/http/indices/delete_index'
require 'eson/http/indices/delete_mapping'
require 'eson/http/indices/flush'
require 'eson/http/indices/get_mapping'
require 'eson/http/indices/get_settings'
require 'eson/http/indices/open_index'
require 'eson/http/indices/optimize'
require 'eson/http/indices/put_mapping'
require 'eson/http/indices/refresh'
require 'eson/http/indices/snapshot'
require 'eson/http/indices/status'
require 'eson/http/indices/put_template'
require 'eson/http/indices/get_template'
require 'eson/http/indices/delete_template'
require 'eson/http/indices/update_settings'
require 'eson/http/indices/exists'
require 'eson/http/indices/stats'
require 'eson/http/indices/segments'